### ISSUE TITLE
Missing map data

### ISSUE THREAD

**Issue by Jaco909** [Derpduck/GG2-Map-Archive#3]
cp_launch, cp_cargo, and ctf_cario are missing map data. I've recompiled and attached them below.

cp_launch
![cp_launch](https://user-images.githubusercontent.com/4472340/135134103-490131e7-e0df-4d22-b82e-1683350e29eb.png)

cp_cargo
![cp_cargo](https://user-images.githubusercontent.com/4472340/135134188-36408a10-3e72-4771-aa6b-66f2a09bdc4d.png)

ctf_cario
![ctf_cairo](https://user-images.githubusercontent.com/4472340/135134239-fc7a5356-318c-48ce-9592-c504711fcd70.png)

**Comment by Jaco909** [comment]
Recompiled ctf_ancient_ruins:
![ctf_ancient_ruins](https://user-images.githubusercontent.com/4472340/135774276-9b06c3ed-2c34-493d-87d5-84cfe6b19785.png)

**Comment by Derpduck** [comment]
Thanks, I've added the files, feel free open pull requests to add the files directly.
